#!/usr/bin/env bash
# Disposable fixture identities only. No enrollment, installation or kernel build.
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
for tool in gpg make objcopy openssl sbsign sbverify; do
    if ! command -v "$tool" >/dev/null; then
        echo "SKIP real crypto integration: missing $tool"
        [[ "${REQUIRE_CRYPTO:-0}" != 1 ]] || exit 1
        exit 77
    fi
done
umask 077
t="$(mktemp -d)"
trap 'gpgconf --homedir "$t/gnupg" --kill all 2>/dev/null || true; find "$t" -depth -delete' EXIT
mkdir "$t/gnupg" "$t/input" "$t/work"
gpg --batch --homedir "$t/gnupg" --pinentry-mode loopback --passphrase '' \
    --quick-generate-key 'Disposable fixture <fixture@example.invalid>' rsa2048 sign 0 >/dev/null 2>&1
fingerprint="$(gpg --homedir "$t/gnupg" --with-colons --list-keys 2>/dev/null | awk -F: '$1=="fpr" {print $10; exit}')"
gpg --homedir "$t/gnupg" --export > "$t/trusted.gpg"
mkdir "$t/input/linux-6.18.53"
printf 'kernelversion:\n\t@echo 6.18.53\n' > "$t/input/linux-6.18.53/Makefile"
tar -cf "$t/archive.tar" -C "$t/input" linux-6.18.53
xz -c "$t/archive.tar" > "$t/linux-6.18.53.tar.xz"
gpg --batch --homedir "$t/gnupg" --pinentry-mode loopback --passphrase '' --detach-sign "$t/archive.tar"
printf 'CONFIG_LOCALVERSION="-fixture"\n# CONFIG_LOCALVERSION_AUTO is not set\n' > "$t/config"
bash "$root/scripts/verify-kernel-source.sh" --version 6.18.53 --localversion -fixture \
    --archive "$t/linux-6.18.53.tar.xz" --sha256 "$(sha256sum "$t/linux-6.18.53.tar.xz" | cut -d' ' -f1)" \
    --signature "$t/archive.tar.sig" --keyring "$t/trusted.gpg" --fingerprint "$fingerprint" \
    --source-dir "$t/work/linux-6.18.53" --config "$t/config"
# Minimal non-booted EFI fixture generated by binutils, not a Linux image.
printf '\303' > "$t/ret.bin"
objcopy -I binary -O pei-x86-64 -B i386:x86-64 --subsystem=10 "$t/ret.bin" "$t/image.efi"
for id in good wrong; do
    openssl req -new -x509 -newkey rsa:2048 -nodes -subj "/CN=Disposable-$id/" \
        -keyout "$t/$id.key" -out "$t/$id.crt" -days 1 >/dev/null 2>&1
done
digest="$(sha256sum "$t/image.efi" | cut -d' ' -f1)"
if bash "$root/scripts/sign-kernel.sh" --key "$t/good.key" --cert "$t/wrong.crt" --kernel "$t/image.efi" --expected-sha256 "$digest" > "$t/reject.log" 2>&1; then
    echo 'FAIL mismatched certificate accepted'; exit 1
fi
[[ "$(sha256sum "$t/image.efi" | cut -d' ' -f1)" == "$digest" ]]
bash "$root/scripts/sign-kernel.sh" --key "$t/good.key" --cert "$t/good.crt" --kernel "$t/image.efi" --expected-sha256 "$digest"
sbverify --cert "$t/good.crt" "$t/image.efi"
if sbverify --cert "$t/wrong.crt" "$t/image.efi"; then echo 'FAIL wrong cert verifies'; exit 1; fi
echo 'PASS real GPG and disposable EFI signature integration'
